language: SQL
dist: bionic
sudo: true

matrix:
  include:
    - name: sql
      env: TEST=sql

    - name: extension
      env: TEST=extension PG=95

    - name: pgxn
      env: TEST=pgxn PG=95

    - name: extension-9.5
      env: TEST=extension PG=95

    - name: extension-9.6
      env: TEST=extension PG=96

    - name: extension-10
      env: TEST=extension PG=10

    - name: extension-11
      env: TEST=extension PG=11

    - name: extension-12
      env: TEST=extension PG=12

    - name: pgxn-9.5
      env: TEST=pgxn PG=95

    - name: pgxn-9.6
      env: TEST=pgxn PG=96

    - name: pgxn-10
      env: TEST=pgxn PG=10

    - name: pgxn-11
      env: TEST=pgxn PG=11

    - name: pgxn-12
      env: TEST=pgxn PG=12

services:
  - docker

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11-postgis-2.5

before_install:
    - psql -c 'create database pgmemento_testdb;' -U postgres
    - psql --version

script:
    - if [[ $TEST == "sql" ]] ; then psql -U postgres -d pgmemento_testdb -a -f TEST.sql ; fi
    - if [[ $TEST == "extension" ]] ; then ./extension/tests/run.sh $PG ; fi
    - if [[ $TEST == "pgxn" ]] ; then ./extension/pgxn/tests/run.sh $PG ; fi
